export const ALL_BOOKS_REMOVE_FROM_CART = 'ALL_BOOKS_REMOVE_FROM_CART';
export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
export const BOOK_REMOVE_FROM_CART = 'BOOK_REMOVE_FROM_CART';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
